services:
  redis:
    image: redis/redis-stack:latest   # includes RedisJSON, Search, Bloom, TimeSeries
    container_name: websitevisits-redis
    ports:
      - "6379:6379"

  node:
    build: .
    container_name: websitevisits-node
    ports:
      - "9090:9090"
    depends_on:
      - redis